### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by Ahmad45123**
Enjoy!

### CODE REVIEW

**Comment by xISRAPILx** [comment]
The translated text is not shown completely.
image

**Comment by Ahmad45123** [comment]
Please do any edits you do in master, don't use translations branch at all.

**Comment by Ahmad45123** [comment]
@xISRAPILx with the new version, includes are now moved into dependencies folder. So you need to move your includes there.
There's two ways: 
* First way *(RECOMMENDED WAY)*: Open the packages window in ExtremeStudio and install the includes you need one by one.. I've looked at your includes and I think all of them do exist there.
* Second way *I don't recommend this but you can do it if your includes doesn't exist in the packages*: Create a folder called `oldincludes` or any other name in `dependencies` folder and move all contents from pawno/includes to there.

**Comment by xISRAPILx** [comment]
@Ahmad45123, the first method does not suit me, the second one does not work.

**Comment by Ahmad45123** [comment]
Yeah I'm mistaken.. I'll push a fix in an hour or less fixing that issue :)

**Comment by Ahmad45123** [comment]
Please continue the conversation at #45

**Pull request merged**
