### PR TITLE
Update IncludesForm.vb

### PR DESCRIPTION
**Pull request by B3LlAT0R**
Link include Streamer.ini no working change by https://github.com/samp-incognito.

### CODE REVIEW

**Comment by Ahmad45123** [comment]
The includes are handled here: https://github.com/Ahmad45123/esfiles/blob/gh-pages/includes.xml

Modify the file to point to the new link and submit a pull request there. (Sorry not on PC and won't be for a while so can't do it myself)

**Comment by B3LlAT0R** [comment]
I think the link put in
https://github.com/Ahmad45123/ExtremeStudio/blob/master/ExtremeStudio/Functions%20Forms/IncludesForm.vb
But ok i doing in xml.


2017-11-25 13:48 GMT-06:00 Ahmed Mamdouh <notifications@github.com>:

**Comment by B3LlAT0R** [comment]
How many Link's i can put?

2017-11-25 14:06 GMT-06:00 Jorge Hernandez <j9a0h1r@gmail.com>:

**Comment by Ahmad45123** [comment]
What do you mean with how many links ?
You can add whatever includes you want if that's what you're asking.

**Comment by Ahmad45123** [comment]
There's also Plugins.xml for plugins

**Comment by B3LlAT0R** [comment]
Ok. thanks Ahmad45123

**Comment by B3LlAT0R** [comment]
Check now the link if it's good. A thousand apologies, I'm new to this

**Pull request closed without merging**
